In [1]:
#import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 

In [7]:
data = pd.read_csv(r"E:\learning\AI1\Machine Learning A-Z - work\Project\Machine-Learning-Projects-With-Python\Tic-Tac-Toe\tic-tac-toe_csv.csv")
#data preprocessing
data_new = pd.get_dummies(data.iloc[:,0:9])
X = data_new.iloc[:, :].values
print(X)
y = data_new.iloc[:, -1].values

[[0 0 1 ... 0 1 0]
 [0 0 1 ... 0 1 0]
 [0 0 1 ... 0 0 1]
 ...
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]]


In [3]:
#Splitted Data into Test and Train set
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.25, random_state = 0)

In [4]:
#Applying logistic Regression model
from sklearn.linear_model  import LogisticRegression
LR = LogisticRegression()
LR = LR.fit(X_train, y_train)

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = LR.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[141   0]
 [  0  99]]


1.0

In [8]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

1.0
[[141   0]
 [  0  99]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       141
           1       1.00      1.00      1.00        99

    accuracy                           1.00       240
   macro avg       1.00      1.00      1.00       240
weighted avg       1.00      1.00      1.00       240

